### PR TITLE
Move `BlockResyncManager.shouldForceSync()` method to PolyMap

### PR DESCRIPTION
**Pull request by skerit**
As I mentioned on Discord: I'm moving all my custom PolyBlock profiles (my precious mushrooms!) from my fork into a separate add-on mod. So I'm really utilizing the PolyMap interface to the fullest now :)

Some of the blocks I'm implementing (mushroom blocks + wall blocks) require a blockstate resync-update to the client.
Currently there's no way of doing this, except from re-implementing all the mixins.

Having this be a part of the PolyMap fixes that.

I do need to add the `world` and `pos` arguments back though, because I especially need those for my mushroom blocks.
(More specifically: They need to check their neighbour/opposite blocks. If the opposite block isn't a mushroom, no resync is needed)

### CODE REVIEW

**Comment by TheEpicBlock** [comment]
The `sourceState` should be the block that caused the block update, so that would be the opposite block. Looking at the mushroom and wall code, that should be enough to decide whether the block needs to be updated. See also the way string is implemented.

**Comment by skerit** [comment]
I'll look into this in a few days! :)

**Comment by skerit** [comment]
@TheEpicBlock Updated it.

I did have to add this check:
https://github.com/skerit/PolyMc/blob/28581abd361cb3ce0f5deeab0ef78223e06fb667/src/main/java/io/github/theepicblock/polymc/impl/misc/BlockResyncManager.java#L55

Because otherwise the sourceState was mostly null, and so the mushroom check wouldn't work anyway.

**Comment by TheEpicBlock** [comment]
I should really move around some of that code to make clear what the states reperesent and to prevent some of the repeated getting of polymaps and such. Either way, that's something for me to do. It makes sense to move the method, and the code looks great :D 
lgtm! It's only been a year :P

**Comment by skerit** [comment]
Thanks!

> lgtm! It's only been a year :P

Well, my `I'll look into this in a few days! :)` was a bit optimistic at the time 😅

**Pull request merged**
