### PR TITLE
Fix more things in 1.20.5 port.

### PR DESCRIPTION
**Pull request by Patbox**
A bit of work on 1.20.5/6 port, improve items and fix some other issues/crashes, making it usable with more mods (tested with PolymaniaForks + my own polymer mods). There are likely still some issues/bugs, so it needs bit more testing.

Depends on https://github.com/TheEpicBlock/resource-locator-api/pull/4

### CODE REVIEW

**Comment by TheKidThatCodes** [comment]
from 1.20.5 changelog, it says:
Invalid data in packets sent from a server will now cause the game client to disconnect
To ease the transition period, modded servers can opt out by setting the appropriate field in the handshake/game_profile packet
This option will be removed in the next release
maybe consider suppressing theese packets?

**Comment by Patbox** [comment]
It's best to not use that and fix the errors instead, as they will cause issues otherwise (and it will be removed, so for people using ViaVersion it's not great idea)

**Comment by TheEpicBlock** [comment]
Just for my understanding, why did you rewrite the tooltip transformer code? I presume to help support mods that mixin to `ItemStack#getTooltip` but I just want to make sure there's not a different reason I'm missing

**Comment by Patbox** [comment]
From my testing it didn't work correctly originally (broke tooltips for items modified with polymer). Also yeah it fixes compat with mods adding things there, like trinkets.

**Comment by TheKidThatCodes** [comment]
> It's best to not use that and fix the errors instead, as they will cause issues otherwise (and it will be removed, so for people using ViaVersion it's not great idea)

thats what i meant, some kind of packet filter or smth to only allow vanilla packets through if client is fully vanilla, but then that might break things like simple voice chat that send non vanilla packets.

**Comment by TheEpicBlock** [comment]
Non-vanilla packets aren't affected by the 1.20.5 change. They use special plugin channel packets which are meant to contain modded/arbitrary data. Instead, the change affects vanilla packets which contain references to modded data. This PR aims to remove/edit those references.

**Comment by TheKidThatCodes** [comment]
is this a good place for issues that are using this pr?
<details>
<summary>Issue</summary>
Velocity -> Fabric

Screenshot 2024-06-10 at 10 53 30 AM


<details>
<summary>output of `ls mods | clipcopy`</summary>

```
1.20.6-2.4.1-1.20.6.jar # telekenisis enchant
AxesAreWeapons-1.8.1-fabric-1.20.5.jar
BetterThanMending-fabric-2.0.2.jar
BlueMap-3.21-fabric-1.20.5.jar
Chunky-1.4.10.jar
ChunkyBorder-1.2.13.jar
Clumps-fabric-1.20.6-17.0.0.1.jar
CraftTweaker-fabric-1.20.6-19.0.8.jar
FabricProxy-Lite-2.8.0.jar
FallingTree-1.20.6-1.20.6.6.jar
FauxCustomEntityData-fabric-1.20.6-11.0.1.jar.disabled
InvView-1.4.15-1.20.5+.jar
Jade-1.20.6-Fabric-14.2.4.jar
Linkart-5.4.4-1.20.6-build.28.jar
LuckPerms-Fabric-5.4.125.jar
NoChatReports-FABRIC-1.20.6-v2.7.0.jar
PolyMc-5.6.1+1.20.6.jar
RecipeCooldown-1.0.0.jar
RoughlyEnoughItems-15.0.728-fabric.jar
StackDeobfuscatorFabric-1.4.2+bf1fc22.jar
TaxFreeLevels-1.3.11-fabric-1.20.5.jar
Terralith_1.20_v2.5.1.jar
VersionCheckerMod-2.4.0.jar
XaerosWorldMap_1.38.8_Fabric_1.20.6.jar
Xaeros_Minimap_24.2.0_Fabric_1.20.6.jar
YetAnotherConfigLib-3.4.4+1.20.6-fabric.jar
accelerated-decay-fabric-86.0.0.jar
alternate-current-mc1.20-1.8.0-beta.4.jar
antixray-fabric-1.4.1+1.20.6.jar
appleskin-fabric-mc1.20.5-3.0.2.jar
architectury-12.1.3-fabric.jar
artifacts-fabric-11.0.0.jar
audioplayer-fabric-1.20.6-1.10.2.jar
bottledair-1.20.6-2.3.jar
brewery-0.7.1+1.20.6.jar
cc-tweaked-1.20.6-fabric-1.111.0.jar
cc-tweaked-polymer-patch-1.111.0.1+1.20.6.jar
chargedcharms-1.20.6-2.0.0.5-FABRIC.jar
charmofundying-fabric-8.0.0+1.20.6.jar
cicada-lib-0.7.2+1.20.5-and-above.jar
cloth-config-14.0.126-fabric.jar
collective-1.20.6-7.61.jar
colorfulhearts-fabric-1.20.6-9.0.1.jar
comforts-fabric-8.0.1+1.20.6.jar
crossstitch-0.1.7.jar
ctov-fabric-3.4.3.jar
data-loader-1.1.6+1.20.5-1.20.6.jar
deathbackup-1.20.6-3.3.jar
do_a_barrel_roll-fabric-3.6.0+1.20.6.jar
economical-villager-trading-1.2.14+MC1.20.2-1.20.6.jar
egapplemod-1.0.0.jar
elytra_trinket-1.0.8.jar
fabric-api-0.100.0+1.20.6.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
ferritecore-6.1.1-fabric.jar
graves-3.3.3+1.20.5.jar
grind-enchantments-3.2.1+1.20.6.jar
guns++-4.5.2.jar
image2map-0.6.0+1.20.6.jar
infinitetrading-1.20.6-4.3.jar
instantgroup-fabric-1.20.6-1.6.0.jar
ironfish-mcmeta-4-41_1.13-1.20.5.jar
jamlib-fabric-1.0.9+1.20.6.jar
jline4mcdsrv-0.5.0.jar
journeymap-1.20.6-5.9.34-fabric.jar
krypton-0.2.7.jar
largefluidtank-fabric-20.14.1.jar
letmedespawn-fabric-1.20.5-1.20.6-1.2.1.jar
lithium-fabric-mc1.20.6-0.12.3.jar
lithostitched-fabric-1.20.5-1.1.7b.jar
luckperms # tis a folder lol
mine-spawners-1.0.jar
moretools-1.3.0+1.20.6.jar
nerb-1.20.6-0.4-FABRIC.jar
no-telemetry-1.8.0.jar
noisium-fabric-2.1.0+mc1.20.5-1.20.6.jar
notenoughcrashes-4.4.7+1.20.6-fabric.jar
omnihopper-2.3.1+1.20.6.jar
polydecorations-0.3.1+1.20.6.jar
polyfactory-0.4.0-pre.2+1.20.6.jar
polymer-bundled-0.8.2+1.20.6.jar
potionring-fabric-1.20.6-1.0.jar
resource-locator-api-0.6.0+1.20.6.jar
rightclickharvest-fabric-4.2.0+1.20.6.jar
scalable-cats-force-fabric-3.0.0.jar
smallernetherportals-1.20.6-3.7.jar
tectonic-fabric-1.20.5-2.3.5.jar
televator-1.1.3+1.20.6.jar
trinkets-3.9.0+polymerport.1.jar
vanish-1.5.5+1.20.6.jar
vcinteraction-fabric-1.20.6-1.0.6.jar
villagebellrecipe-1.20.6-3.4.jar
voicechat-fabric-1.20.6-2.5.15.jar
```

</details>

</details>

**Comment by TheEpicBlock** [comment]
This has been merged manually, thanks!

**Pull request closed without merging**
