### PR TITLE
Add ArmorItem & ArmorMaterial polys with FancyPants support

### PR DESCRIPTION
**Pull request by skerit**
Added polys for ArmorItems & ArmorMaterials, together with FancyPants shaders.
The generation of the images is based on @Patbox's implementation in Polymer.

Because FancyPants requires the original leather textures, I had to add a way of getting the client jar, which I implemented the same way @Patbox did.

Because the client jar is now available, I also removed all the `if (modId.equals("minecraft")) return null; //we can't access minecraft resources easily` lines.

### CODE REVIEW

**Comment by CamperSamu** [comment]
Just did a local fork to merge master and this branch, I can confirm it still works in 1.18.1.
image

**Comment by Patbox** [comment]
This pr doesn't seem to handle vanilla leather armors having the same values as ones taken by PolyMC (Polymer's implementation handles that). It might be an issue you want to look into before it's merged

**Comment by CamperSamu** [comment]
Yeah I had that concern too, taking the rgb color value and rounding it _should_ be enough but for now I'm blocking leather armor until I (or someone) thinks of a better solution.

**Comment by TheEpicBlock** [comment]
The resource rewrite is done now, so I'll start looking into getting this into master

**Comment by Patbox** [comment]
> Yeah I had that concern too, taking the rgb color value and rounding it to the first available color _should_ be enough but for now I'm blocking leather armor until I (or someone) thinks of a better solution.

Yeah, adding 1 to any coliding value should fix that

**Comment by skerit** [comment]
I merged the upstream changes back into this branch.

@Patbox I couldn't really find where you work around PolyMC potentially haven taken similar color values, could you point me in the right direction?

Maybe we should also exclude any value that's obtainable via vanilla dyeing methods?

**Comment by Patbox** [comment]
> I merged the upstream changes back into this branch.
> 
> @Patbox I couldn't really find where you work around PolyMC potentially haven taken similar color values, could you point me in the right direction?
> 
> Maybe we should also exclude any value that's obtainable via vanilla dyeing methods?

Polymer just marks these items as "server side" ones, see https://github.com/Patbox/polymer/blob/dev/1.18.1/polymer/src/main/java/eu/pb4/polymer/api/item/PolymerItemUtils.java#L162

For PolyMC you most likely could add that in similar place (look where it handles modded enchantments for vanilla items)

**Pull request merged**
